### ISSUE TITLE
Better explanation how to use the API

### ISSUE THREAD

**Issue by OpenSource03** [Nathan-Nesbitt/Minecraft_API#70]
Hi there!

First of all, I'd like to ask if this API still works and supports the newest Education Edition?

Second, would you please be able to explain in a little more detail how to use it? As far as I was able to understand, we need to insert the code to the code editor inside Minecraft Education Edition (one of these that open when you click c), but I wasn't able to find a way to import this library there.

I want to have an app that will receive all the events from education edition as those happen through websocket.

Thanks!

**Comment by p0t4t0sandwich** [comment]
Same boat here, trying to dig around to see if any of this could be used for player management, since Microsoft refuses  to release a proper developer API, and addons don't have any decent programmatic ways to solve these sorts of problems.
Doesn't help that Microsoft's documentation is abysmal for this product.

**Comment by himemleung** [comment]
can't connect with minecraft education v.1.19.52. When I try /connect localhost:5678, the following error appear:

Error in connection handler
Traceback (most recent call last):
  File "site-packages\websockets\protocol.py", line 827, in transfer_data
  File "site-packages\websockets\protocol.py", line 895, in read_message
  File "site-packages\websockets\protocol.py", line 977, in read_data_frame
  File "site-packages\websockets\framing.py", line 308, in parse_close
  File "site-packages\websockets\framing.py", line 338, in check_close
websockets.exceptions.ProtocolError: invalid status code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "site-packages\websockets\server.py", line 191, in handler
  File "src\back_end\broker.py", line 44, in response
  File "site-packages\websockets\protocol.py", line 509, in recv
  File "site-packages\websockets\protocol.py", line 812, in ensure_open
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

**Comment by p0t4t0sandwich** [comment]
Found some resources on how the websocket messages actually work:
https://gist.github.com/pirosuke/1ca2aa4d8920f41dfbabcbc7dc2a669f
https://gist.github.com/jocopa3/5f718f4198f1ea91a37e3a9da468675c

**Comment by Nathan-Nesbitt** [comment]
> Hi there!
> 
> First of all, I'd like to ask if this API still works and supports the newest Education Edition?
> 
> Second, would you please be able to explain in a little more detail how to use it? As far as I was able to understand, we need to insert the code to the code editor inside Minecraft Education Edition (one of these that open when you click c), but I wasn't able to find a way to import this library there.
> 
> I want to have an app that will receive all the events from education edition as those happen through websocket.
> 
> Thanks!

Hey @OpenSource03 the main project can be found here which uses this API to make calls: https://github.com/Nathan-Nesbitt/Minecraft_AI

This project is not officially supported, saying that if anyone would like to create PRs for fixes to add onto this project I will review / accept them on a separate branch (I don't want to break the original code, unless someone can find the list up updated commands @p0t4t0sandwich and we can fix everything at once).

The idea is pretty straight forward, there is a way to open a browser in Minecraft education edition which allows you to open a webpage in the app. The game has ports open which allows it to accept and send information over websockets, this library outlined the accepted commands *2 years ago* so you may have to update some of this code.

If you wanted to use this library directly, you can either create a localhost REST server that serves up a webpage that can be opened within the application (if you want to interact with this library visually) OR you can just inject this library into a NodeJS application that is running locally based on the main project code and just send and receive commands in the background.

Cheers hope this helps! :)

**Comment by Nathan-Nesbitt** [comment]
> Same boat here, trying to dig around to see if any of this could be used for player management, since Microsoft refuses to release a proper developer API, and addons don't have any decent programmatic ways to solve these sorts of problems. Doesn't help that Microsoft's documentation is abysmal for this product.

I'm linking to the response on the main API just for reference: https://github.com/Nathan-Nesbitt/Minecraft_AI/issues/69#issuecomment-1567622105

**Comment by Nathan-Nesbitt** [comment]
> can't connect with minecraft education v.1.19.52. When I try /connect localhost:5678, the following error appear:
> 
> Error in connection handler Traceback (most recent call last): File "site-packages\websockets\protocol.py", line 827, in transfer_data File "site-packages\websockets\protocol.py", line 895, in read_message File "site-packages\websockets\protocol.py", line 977, in read_data_frame File "site-packages\websockets\framing.py", line 308, in parse_close File "site-packages\websockets\framing.py", line 338, in check_close websockets.exceptions.ProtocolError: invalid status code
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "site-packages\websockets\server.py", line 191, in handler File "src\back_end\broker.py", line 44, in response File "site-packages\websockets\protocol.py", line 509, in recv File "site-packages\websockets\protocol.py", line 812, in ensure_open websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

Just linking for reference: https://github.com/Nathan-Nesbitt/Minecraft_AI/issues/69#issuecomment-1567622105

**Comment by Nathan-Nesbitt** [comment]
> Same boat here, trying to dig around to see if any of this could be used for player management, since Microsoft refuses to release a proper developer API, and addons don't have any decent programmatic ways to solve these sorts of problems. Doesn't help that Microsoft's documentation is abysmal for this product.

This may be possible, it's been a while since I've looked at this but this is the main file of events that were supported when I originally wrote this:

https://github.com/Nathan-Nesbitt/Minecraft_API/blob/22412a6cd0a1205b8724365bec3d8c2ca1ed5700/src/events.js

The events likely have changed over time and would require updating based on what has been opened up / closed / renamed since this was developed. As it's not an officially supported project, unfortunately there's no guarantee that this will be the same as 2 years ago.

**Comment by p0t4t0sandwich** [comment]
Just to update on my own progress, I've built a full WS API, with the capabilities to handle multiple connections, a built-in REST API, and a general command handler for users to run commands that don't have defined message types/responses yet (along with generic Event response types for undefined events).
I also have a mostly-functional plugin loading system to allow users to expand as they please.

I don't have it published as a proper package yet, as it needs more work, but it's getting there!
(Project is written in TypeScript)
