### ISSUE TITLE
Possible to use with App Inventor?

### ISSUE THREAD

**Issue by himemleung** [Nathan-Nesbitt/Minecraft_API#71]
Is it possible to use your API to integrate App Inventor and MC education? My kids used code connection before as REST server so he can control MC agent thru url. However, code connection no longer support latest MC education. I am looking for your api to see can replace code connection.

Remark: The code editor inside MC education does not listen any port so we can't call from App inventor to MC Education.

**Comment by p0t4t0sandwich** [comment]
I'm currently working on an up to date implementation that should be functional with the latest version of MC EduE.
If all goes well I'm planning on adding a REST API on top of all the websocket functionality, and hopefully that will make for an easier interface to work with.

**Comment by Nathan-Nesbitt** [comment]
> Is it possible to use your API to integrate App Inventor and MC education? My kids used code connection before as REST server so he can control MC agent thru url. However, code connection no longer support latest MC education. I am looking for your api to see can replace code connection.
> 
> Remark: The code editor inside MC education does not listen any port so we can't call from App inventor to MC Education.

I'm gonna say it'd be a little difficult to get it integrated with App Inventor unless they wanted to implement an integration and maintain the endpoints and all the possible integrations. 

Sounds like you would be looking for Code Connection which is a supported version without AI by the Mojang team: 

https://educommunity.minecraft.net/hc/en-us/articles/360047555251-Get-Started-With-Code-Connection-
